bcgov/nr-rec-resources

infrastructure/api/autoscaling.tf
This PR fixes scale down policy which was impacting scale down of tasks
=> fix: autoscaling - scale down policy

.github/ISSUE_TEMPLATE/task-template.md
Removed reference to given, when, then, and definition of done and ready.
=> docs: update issue templates

.github/ISSUE_TEMPLATE/epic.md
=> docs: update epic.md

.github/workflows/build-deploy-el-openshift.yml, .pre-commit-config.yaml, charts/backend-el/Chart.yaml, charts/backend-el/templates/_helpers.tpl, charts/backend-el/templates/cronjob.yaml, charts/backend-el/templates/pvc.yaml, charts/backend-el/templates/secret.yaml, charts/backend-el/values.yaml
This PR is only to add the pipeline and charts, it will be tested later when OpenShift namespace is provisioned and the Proxy Account is created to connect to oracle.
All the fixes and updates will be done later. 
This needs to be merged to main so that manual workflow dispatch action can be triggered and tested.
TODO
=> feat: adding backend el build deploy for openshift

.commitlintrc.yml
Increase header length and allow capital letters in subject. Apologies to any developers who this annoyed.
=> update commitlint rules

migrations/fta/sql/V1.0.1__import_csv_from_s3.sql
=> chore: import recreation map feature code data from s3

.github/workflows/openshift-oracle-s3-sync.yml
Fix includes creating the tf deploy ARN into openshift-dev environment in Github
=> fix: s3 secret sync

.github/workflows/build-deploy-el-openshift.yml, .github/workflows/main.yml
This PR separates openshift and aws triggers with path matching.
=> chore: pipeline changes to handle openshift ignores

.github/workflows/main.yml, backend-el/run_app.sh
This PR changes the GC used in the app from ZGC to ParallelGC, as the ZGC is more geared towards high amount Heap , more than 100Gigs.
=> fix: move to parallelgc from zgc

.github/workflows/scheduled.yml, CONTRIBUTING.md, README.md, docs/ci.md, docs/deployment.md, docs/open-api-swagger.md
Update our documentation to clarify and fix some missing local setup steps and add some basic deployment and AWS logging and query editor instructions.
Also added a table of contents, moved the Swagger docs to its own file and fixed the schemaspy action directory.
=> documentation updates

backend/src/recreation-resource/recreation-resource.service.spec.ts, backend/src/recreation-resource/recreation-resource.service.ts
=> chore: order things to do filter options alphabetically

backend-el/src/main/java/ca/bc/gov/nrs/environment/fta/el/services/ApplicationService.java
=> fix: corrected column order to fit under the correct column header

frontend/src/components/layout/BetaBanner.scss, frontend/src/components/layout/BetaBanner.test.tsx, frontend/src/components/layout/BetaBanner.tsx, frontend/src/components/layout/Header.scss, frontend/src/components/layout/Header.tsx, frontend/src/hooks/useMediaQuery.test.ts, frontend/src/hooks/useMediaQuery.ts
Implements beta banner and beta tag for all pages.
Fixes # (171)
=> feat(banner): added beta banner

frontend/src/components/layout/Footer.tsx, frontend/src/components/rec-resource/section/Contact.tsx, frontend/src/data/urls.ts
=> chore: add contact url

frontend/src/components/layout/Footer.tsx
=> chore: fix footer links

frontend/src/components/landing-page/LandingPage.tsx, frontend/src/components/layout/BetaBanner.scss, frontend/src/components/layout/BetaBanner.test.tsx, frontend/src/components/layout/BetaBanner.tsx, frontend/src/data/urls.ts, frontend/src/styles/global.scss
- Added link to feedback form as mentioned in the ticket: #160 
- Modifed the feedback button in the beta banner as per the figma design
[localhost-screenshots.zip](https://github.com/user-attachments/files/19675429/localhost-screenshots.zip)
=> feat(feedback-link): added links to feedback form

backend/package.json, frontend/src/components/landing-page/components/recreation-search-banner/RecreationSearchBanner.scss, frontend/src/components/landing-page/components/recreation-search-banner/RecreationSearchBanner.test.tsx, frontend/src/components/landing-page/components/recreation-search-banner/RecreationSearchBanner.tsx, frontend/src/components/layout/Header.scss, frontend/src/components/layout/Header.tsx, frontend/src/components/rec-resource/RecResource.scss, frontend/src/components/rec-resource/RecResourcePage.tsx, frontend/src/components/recreation-search-form/RecreationSearchForm.tsx, frontend/src/components/search/Search.scss, frontend/src/components/search/SearchBanner.tsx, frontend/src/components/search/SearchPage.tsx, frontend/src/components/search/filters/FilterChip.tsx, frontend/src/components/search/filters/Filters.scss, frontend/src/styles/global.scss, frontend/src/styles/variables.scss
Added spacing tweaks and layout modifications in the **Search** page based on the design in this ticket: #489
=> fix(search-page): modified layout to add spacing tweaks to fit the new design

.github/workflows/.aws-deployer.yml, .github/workflows/.deploy-app.yml, .github/workflows/build-deploy-el-openshift.yml, .github/workflows/main.yml, .github/workflows/openshift-oracle-s3-sync.yml, charts/backend-el/templates/secret.yaml, charts/backend-el/values.yaml, infrastructure/api/ecs.tf, infrastructure/api/iam.tf, infrastructure/database/aurora-v2.tf, infrastructure/database/iam.tf, infrastructure/migration/ecs.tf, infrastructure/migration/vars.tf, infrastructure/modules/ecs-flyway-task/main.tf, migrations/fta/sql/V1.0.1__import_csv_from_s3.sql, migrations/fta/sql/V1.1.11__fta_to_rst_map_feature.sql, migrations/rst/entrypoint.sh, terraform/api/prod/terragrunt.hcl, terraform/database/prod/terragrunt.hcl, terraform/frontend/prod/terragrunt.hcl, terraform/migration/prod/terragrunt.hcl
=> ci: deploy to prod

bcgovpubcode.yml
=> chore: add bcgovpubcode.yml

frontend/e2e/enum/search.ts, frontend/src/components/search/NoResults.tsx, frontend/src/components/search/SearchPage.test.tsx, frontend/src/components/search/SearchPage.tsx
=> chore: update search page no results message

backend/src/prisma.service.ts, infrastructure/api/autoscaling.tf, infrastructure/api/vars.tf, terraform/api/prod/terragrunt.hcl, terraform/api/test/terragrunt.hcl, terraform/database/prod/terragrunt.hcl
=> ci: adjust prod deployment resources

frontend/src/components/layout/Footer.scss, frontend/src/components/layout/Footer.tsx
Added land acknowledgement section to the site footer.
---
---
=> feat(footer): add land acknowledgement

.github/workflows/fta-migration.yml
Scheduler cron time was wrong, needs to be in UTC
=> fix(ci): fta scheduler utc time

frontend/e2e/enum/search.ts, frontend/src/components/search/NoResults.scss, frontend/src/components/search/NoResults.test.tsx, frontend/src/components/search/NoResults.tsx, frontend/src/components/search/Search.scss, frontend/src/components/search/SearchPage.test.tsx, frontend/src/components/search/SearchPage.tsx
Adjustments on No Results and search page to make them look more like BC Parks.
- Search filter added to search results
- No Results rendered at the end if totalCount equals 0
=> chore: no results page improvements

backend/src/recreation-resource/service/recreation-resource-search.service.ts
Noticed that I missed an acceptance criteria where results are sorted by closest location if searching by location.
I did a test push to dev and verified that the results are sorted by distance where in test currently they are still sorted by name.
=> core: location search sort by closest result

frontend/src/components/rec-resource/RecResourcePage.test.tsx, frontend/src/components/rec-resource/enum.ts, frontend/src/components/rec-resource/section/SiteDescription.test.tsx
=> chore: rename site description section to description

frontend/src/components/search/Search.scss, frontend/src/components/search/SearchPage.tsx
Assure that the no results text always show on top.
=> chore: fix no result layout

frontend/src/components/landing-page/components/recreation-search-banner/RecreationSearchBanner.scss, frontend/src/components/recreation-search-form/RecreationSearchForm.tsx
=> fix: landing page search responsive layout

frontend/src/components/layout/PageMenu.scss
=> fix: rec resource page menu sticky breakpoint

frontend/src/components/search/filters/Filters.scss
Fix the background on Show All filters.
=> chore: set transparent background to button link

frontend/src/components/layout/BreadCrumbs.tsx, frontend/src/components/search/filters/FilterGroup.test.tsx, frontend/src/components/search/filters/FilterGroup.tsx
=> chore: update filter group and breadcrumb aria label

frontend/src/components/search/NoResults.test.tsx, frontend/src/components/search/NoResults.tsx
=> chore: add no results componenent focus

frontend/e2e/workflows/search/filter.spec.ts, frontend/e2e/workflows/search/filterChips.spec.ts
=> fix(e2e-search-filters): modified test workflow to choose valid filters

frontend/src/components/rec-resource/card/CardCarousel.tsx, frontend/src/components/rec-resource/card/RecResourceCard.scss, frontend/src/components/recreation-search-form/LocationSearch.test.tsx, frontend/src/components/recreation-search-form/LocationSearch.tsx
Minor updates Airlia asked for
- Fix mobile search card spacing on certain phones mentioned here: https://github.com/bcgov/nr-rec-resources/issues/535#issuecomment-2885326676
- Change `Near a community` to `Near a city` in the location search
=> chore: update card styles and location search placeholder

public/frontend/e2e/poms/pages/landing.ts, public/frontend/src/components/landing-page/LandingPage.tsx, public/frontend/src/components/rec-resource/section/Contact.tsx, public/frontend/src/components/rec-resource/section/SiteDescription.tsx, public/frontend/src/routes/AppRoutes.test.tsx, public/frontend/src/routes/constants.ts
=> chore: public site text updates

public/frontend/src/components/layout/Footer.tsx
Fix Land acknowledgement text on footer.
=> chore: fix land acknowledge text

infrastructure/modules/ecs-flyway-task/main.tf
#871
This looks to fix the flakey migrations task by retrying up to 5 times if it doesn't return an arn.
=> fix(ci): invalid taskid deployment error

admin/backend/Dockerfile, admin/backend/package-lock.json, admin/backend/package.json, admin/backend/src/app.module.ts, admin/backend/src/health.controller.ts, admin/backend/test/app.module.spec.ts, admin/backend/test/health.controller.spec.ts, admin/backend/tsconfig.json
#920
Adds health check and uncomment prisma in Dockerfile.
=> fix: add health check for admin deployment

admin/backend/src/recreation-resource/recreation-resource.service.ts, admin/backend/test/recreation-resource/recreation-resource.service.spec.ts, admin/frontend/src/services/recreation-resource-admin/.openapi-generator/FILES
add validation filters to the suggestion results to exclude invalid data.
=> feat(admin-rec-suggestions): added filters in suggestion result to exclude invalid data

admin/backend/src/dam-api/dam-api.ts, admin/backend/src/recreation-resource/dtos/suggestions-response.dto.ts, admin/backend/src/resource-docs/dto/recreation-resource-doc.dto.ts, admin/backend/src/resource-docs/resource-docs.controller.ts, admin/backend/src/resource-docs/service/resource-docs.service.ts, admin/backend/test/dam-api/dam-api.spec.ts, admin/backend/test/resource-docs/dto/recreation-resource-doc.dto.spec.ts, admin/backend/test/resource-docs/resource-docs.controller.spec.ts
-  added title for the file to be uploaded
- fixed the swagger decorators to generate correct client sdk
=> fix(admin-pdf-backend): added title for the file to be uploaded

public/frontend/src/components/rec-resource/RecreationResourceMap/constants.ts
=> chore: fix map icons locations

admin/frontend/src/pages/rec-resource-page/components/RecResourceFileSection/DeleteFileModal.tsx, admin/frontend/src/pages/rec-resource-page/components/RecResourceFileSection/GalleryAccordion.scss, admin/frontend/src/pages/rec-resource-page/components/RecResourceFileSection/RecResourceFileSection.tsx, admin/frontend/test/pages/rec-resource-page/components/RecResourceFileSection/DeleteFileModal.test.tsx
Update UI texts on PDF uploads.
=> chore: update UI text for doc uploads

.github/workflows/.deploy-app.yml, public/frontend/src/components/search/SearchPage.test.tsx
Fix for flakey `SearchPage.test.tsx` in ci
=> fix: flakey search page test in ci

public/frontend/e2e/poms/pages/landing.ts, public/frontend/src/components/landing-page/LandingPage.tsx, public/frontend/src/components/landing-page/components/content-section/ContentSection.scss, public/frontend/src/components/landing-page/components/content-section/ContentSection.tsx, public/frontend/src/components/layout/Header.tsx, public/frontend/src/components/search/SearchPage.tsx, public/frontend/src/components/search/hooks/useClearFilters.ts, public/frontend/src/data/urls.ts
=> chore: update landing page map info

public/frontend/src/components/landing-page/components/recreation-search-banner/RecreationSearchBanner.test.tsx, public/frontend/src/components/landing-page/components/recreation-search-banner/RecreationSearchBanner.tsx, public/frontend/src/components/recreation-suggestion-form/RecreationSuggestionForm.test.tsx, public/frontend/src/components/recreation-suggestion-form/RecreationSuggestionForm.tsx, public/frontend/src/components/search-map/SearchMap.test.tsx, public/frontend/src/components/search-map/SearchMap.tsx, public/frontend/src/components/search-map/SearchViewControls.tsx, public/frontend/src/components/search-map/hooks/useZoomToExtent.ts, public/frontend/src/components/search-map/layers/recreationFeatureLayer.ts, public/frontend/src/components/search/SearchBanner.tsx, public/frontend/src/components/search/filters/FilterMenuSearchMap.test.tsx, public/frontend/src/components/search/filters/FilterMenuSearchMap.tsx, public/frontend/src/components/search/hooks/useFilterHandler.ts
#1074 
also snuck in a small bug fix for preventing zoom logic on clearing the search input on the map page.
=> feat: search map matomo tracking

.github/workflows/.deploy-app.yml, admin/backend/.dockerignore, admin/frontend/.dockerignore, infrastructure/frontend/cloudfront.tf, public/backend/.dockerignore, public/frontend/.dockerignore
#853 and #854
The hidden files is a false positive though I've excluded hidden files from our docker images and s3 upload to be safe. It still didn't fix the issue.
Permissions policy is set, only allowing geolocation and fullscreen:
=> chore: exclude hidden files from docker build context and s3 upload and set permissions policy headers

public/frontend/src/components/rec-resource/RecreationResourceMap/MapDisclaimerModal.scss, public/frontend/src/components/rec-resource/RecreationResourceMap/MapDisclaimerModal.tsx
Just a tiny update, Harry asked to make the label clickable.
=> chore: add label to map disclaimer checkbox

.github/workflows/build-deploy-el-openshift.yml
Fix for OpenShift deployment env vars I missed. Tested by deploying this PR via the Actions tab and it's running well in dev.
=> chore: update flyway task lza env var

public/frontend/src/components/rec-resource/RecResourceReservation.scss, public/frontend/src/components/rec-resource/RecResourceReservation.tsx
Align camping icon to the top of the text as requested.
=> chore: fix icon alignment

.github/workflows/matomo-deploy.yaml, README.md
changed the deploy role arn variable since we swtiched to lza account
=> chore: change the variable name for aws deploy role arn to get the new lza role

public/frontend/src/components/rec-resource/enum.ts, public/frontend/src/components/rec-resource/section/Contact.test.tsx, public/frontend/src/components/rec-resource/section/Contact.tsx, public/frontend/src/components/rec-resource/section/KnowBeforeYouGo.tsx
=> chore: capitalization fixes

public/frontend/src/components/rec-resource/RecResourcePage.test.tsx, public/frontend/src/components/rec-resource/RecResourcePage.tsx, public/frontend/src/components/rec-resource/RecResourceReservation.test.tsx, public/frontend/src/components/rec-resource/RecResourceReservation.tsx, public/frontend/src/components/rec-resource/section/KnowBeforeYouGo.scss, public/frontend/src/components/rec-resource/section/KnowBeforeYouGo.test.tsx, public/frontend/src/components/rec-resource/section/KnowBeforeYouGo.tsx
=> chore: text adjustments

migrations/fta/sql/V1.1.17__fta_to_rstrecreation_agreement_holder.sql
Import even the expired agreement holders.
=> chore: remove expired filter

.github/workflows/.analysis.yml, .github/workflows/.release.yml
Seems like this is working well, just need to make a couple more tweaks thanks.
=> ci: minor release updates

public/frontend/src/components/rec-resource/RecreationResourceMap/RecreationResourceMap.test.tsx, public/frontend/src/components/rec-resource/RecreationResourceMap/RecreationResourceMap.tsx, public/frontend/src/components/rec-resource/RecreationResourceMap/helpers/coordinatesConcersion.test.ts, public/frontend/src/components/rec-resource/RecreationResourceMap/helpers/coordinatesConversion.ts, public/frontend/src/components/rec-resource/RecreationResourceMap/helpers/index.ts
=> chore: added google maps link
