infrastructure/api/ecs.tf

This PR fixes container dependency between flyway and Node API and also added flyway  connection retries
some documentation links for the related change
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/example_task_definitions.html#example_task_definition-containerdependency
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDependency.html
https://documentation.red-gate.com/fd/connect-retries-224919684.html

fix: container dependency , api container should only start when flyway completes successfully

---

infrastructure/api/ecs.tf
infrastructure/api/vars.tf

This PR introduces changes how API workloads are scheduled in ECS with fargate and fargate spot.
vars are defined so numbers can be configured differently for different environment.
links:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-capacity-providers.html

chore(cd): infra changes for ecs

---

.github/workflows/.analysis.yml
.github/workflows/deploy-pr.yml
.github/workflows/main.yml
frontend/package-lock.json
frontend/package.json

Fixing a few bugs from the PR refactor:
- Trivy is working correctly now, also had to delete the stale config from the GitHub UI
- Moved Analysis results job so we can set a status check on it
- Removed broken `needs` dependency from `deploy-pr` job since
- Updated some frontend packages

chore: remove deploy-pr dependency

---

.github/workflows/main.yml

To prevent cancelled deployments from multiple merges to main in succession we are conditionally setting `cancel-in-progress: true`.

chore: ci cancel-in-progress except on main branch

---

migrations/sql/V1.0.0__init.sql
migrations/sql/V1.0.1__rst_db.sql

This PR recreates the RST portion of the FTA Oracle database in Postgres.
As discussed this will live in a separate schema called `fta` in our database and we will migrate the CSV dump to this schema. From there we will be able to shape the database as we see fit in our main `rst` schema.

chore: add rst portion of fta database tables to migration file

---

.github/workflows/.analysis.yml

Not sure why this is passing sometimes, it seems like the scan doesn't start. Though this should fix it according to sonarcloud - `sonar.projectKey=bcgov-sonarcloud_nr-rec-resources-backend`. 
If not I will make a `sonarcloud.properties` file like normal.

ci: fix sonarcloud path

---

.github/workflows/.analysis.yml
.github/workflows/retry-workflow.yml

Trivy sarif-upload is being flaky some days so using the `retry-workflow`. It's not an ideal solution though should mitigate some toil, we will keep an eye on this and perhaps come up with another solution if it still fails.
It should now retry 3 times before failing. Though workflows aren't available through the github cli before merging to main so I was unable to test this completely.

ci: re-run trivy workflow on failure

---

renovate.json

This PR updates the renovate config to ignore patch updates for AWS SDK , they are very noisy

chore: update renovate config to ignore path aws sdk updates

---

.github/workflows/fta-migration.yml
.github/workflows/main.yml
infrastructure/api/ecs.tf
infrastructure/api/network.tf
infrastructure/database/network.tf
infrastructure/frontend/network.tf
infrastructure/migration/network.tf
terraform/api/test/terragrunt.hcl
terraform/database/test/terragrunt.hcl
terraform/frontend/test/terragrunt.hcl
terraform/migration/test/terragrunt.hcl

Adding a new test environment to our deployment pipeline (github workflows) to enable better testing and validation of changes before they reach production.
The following tests were performed to verify the new environment setup:
This change introduces a dedicated test environment in our deployment pipeline to improve our testing capabilities. The new environment will sit between `dev` and `prod` environments, allowing for more thorough testing of features before they reach `prod`.

chore(test-env): add new environment named test in the deployment pipeline

---

frontend/package-lock.json
frontend/src/components/layout/PageMenu.tsx
frontend/src/components/rec-resource/Camping.tsx
frontend/src/components/rec-resource/Closures.tsx
frontend/src/components/rec-resource/RecResourcePage.tsx

Follow up for a couple of bugs introduced in #157, I noticed in pages without closures if you scroll down and then scroll back up the top selection in the page menu won't highlight. This is due to the conditional section ref not being in the page.
- added the missing closures menu 🤦 
- refactored the menu array to better handle conditional sections

fix: pagemenu conditional section scrolling issues

---

backend/prisma/schema.prisma
backend/src/recreation-resource/dto/recreation-resource.dto.spec.ts
backend/src/recreation-resource/dto/recreation-resource.dto.ts
backend/src/recreation-resource/recreation-resource.controller.spec.ts
backend/src/recreation-resource/recreation-resource.service.spec.ts
backend/src/recreation-resource/recreation-resource.service.ts
frontend/src/components/rec-resource/RecResourcePage.test.tsx
frontend/src/components/rec-resource/RecResourcePage.tsx
frontend/src/components/rec-resource/card/RecResourceCard.tsx
frontend/src/components/rec-resource/types.ts
frontend/src/components/search/SearchPage.test.tsx
frontend/src/service/recreation-resource/models/RecreationResourceDto.ts
migrations/fixtures/sql/V1.0.0__recreation_resource.sql
migrations/fta/sql/V1.0.2__fta_to_rst.sql
migrations/rst/sql/V1.0.0__init.sql

[#331](https://github.com/bcgov/nr-rec-resources/issues/331)
Renaming the `recreation_resource` column `site_location` to `closest_community` to better align with business logic.

refactor: rename recreation_resources site_location to closest_community

---

infrastructure/api/ecs.tf
migrations/rst/entrypoint.sh

This pull request extends the functionality of Flyway's clean command to include an option for running in the 'test' environment.

fix(test-env): enabled flyway clean to run in 'test' environment.

---

backend/prisma/schema.prisma
backend/src/recreation-resource/dto/recreation-resource.dto.spec.ts
backend/src/recreation-resource/dto/recreation-resource.dto.ts
backend/src/recreation-resource/recreation-resource.service.spec.ts
backend/src/recreation-resource/recreation-resource.service.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/rec-resource/Camping.test.tsx
frontend/src/components/rec-resource/Camping.tsx
frontend/src/components/rec-resource/RecResourcePage.tsx
frontend/src/components/rec-resource/types.ts
frontend/src/service/recreation-resource/models/RecreationResourceDto.ts
migrations/fixtures/sql/V1.0.0__recreation_resource.sql
migrations/fta/sql/V1.0.2__fta_to_rst.sql
migrations/rst/sql/V1.0.0__init.sql

This feature adds number of campsites to a specific trail.
Fixes # (267)

feat(trail): add number of campsites to trail

---

frontend/src/components/rec-resource/card/CardCarousel.tsx
frontend/src/components/rec-resource/card/RecResourceCard.scss

Fix for resource image dimensions in search page cards.
Images with greater height appear distorted in desktop view due to improper sizing. Implemented object-fit: cover to maintain aspect ratio while properly filling the card space.

fix: adjust resource image dimensions in search page cards

---

frontend/src/components/rec-resource/card/RecResourceCard.test.tsx
frontend/src/components/rec-resource/card/RecResourceCard.tsx

Added rec resource type to the search cards in Search Page.

feat: add rec resource type to the search cards

---

frontend/src/components/RSTSVGLogo/RSTSVGLogo.scss
frontend/src/components/RSTSVGLogo/RSTSVGLogo.test.tsx
frontend/src/components/RSTSVGLogo/RSTSVGLogo.tsx
frontend/src/components/rec-resource/RecResourcePage.test.tsx
frontend/src/components/rec-resource/card/RecResourceCard.scss
frontend/src/components/rec-resource/card/RecResourceCard.test.tsx
frontend/src/components/rec-resource/card/RecResourceCard.tsx
frontend/vitest.config.mts

added placeholder images in the search cards for recreation resources that dont have any images

feat: add placeholder images in search page cards

---

.github/workflows/main.yml

#396 
Use individual job concurrency groups to solve the job concurrency forcing us to manually cancel the previous job on merge to main

ci: concurrency updates

---

frontend/src/components/StyledVectorFeatureMap/hooks/useAddVectorLayerToMap.test.ts
frontend/src/components/StyledVectorFeatureMap/hooks/useAddVectorLayerToMap.ts

Bug: Map Centering 
The map sometimes fails to center on the recreation resource's feature geometry.
Root cause: sometimes the extent of the new vector layer (rec site/trial) is fit before the map has finished rendering
Solution: We now center the map after confirming full render completion.

fix: center the map on the rec resource feature geometry once map is rendered

---

frontend/src/components/search/Search.scss
frontend/src/components/search/SearchBanner.test.tsx
frontend/src/components/search/SearchBanner.tsx

Add `x` button to clear the search field when user types something in the search bar
Fixes # (416)

fix(search): enhanced search

---

Makefile
README.md

As discussed at standup, changed the Makefile to use flyway for migration.Hopefully better catch migration versioning errors earlier. 
Perhaps in the future we can also add a check in ci.

chore: change make db migration commands to use flyway

---

backend/src/recreation-resource/dto/recreation-resource.dto.spec.ts
backend/src/recreation-resource/dto/recreation-resource.dto.ts
backend/src/recreation-resource/recreation-resource.service.spec.ts
backend/src/recreation-resource/recreation-resource.service.ts
backend/src/recreation-resource/test/mock-data.test.ts
frontend/src/components/rec-resource/Camping.test.tsx
frontend/src/components/rec-resource/Camping.tsx
frontend/src/components/rec-resource/RecResourcePage.tsx
frontend/src/components/rec-resource/RecreationFee.test.tsx
frontend/src/components/rec-resource/RecreationFee.tsx
frontend/src/service/recreation-resource/models/RecreationResourceDetailDto.ts
frontend/src/service/recreation-resource/models/RecreationResourceDto.ts

Fixes duplicate issue campsite fees and additional fees for recreation sites.
Fixes # (456)

fix(fees): fix duplicate fees issue

---

frontend/src/components/search/SearchPage.test.tsx
frontend/src/components/search/SearchPage.tsx
frontend/src/service/queries/recreation-resource/recreationResourceQueries.ts

This PR addresses an issue with the search results pagination where newly loaded items weren't properly scrolled into view.
- Implemented scroll behaviour after loading more search results where the page is automatically scrolled to the last item of the previous list.
- Added setTimeout to ensure DOM updates complete before scrolling

fix(search): add scroll behavior after loading more items

---

Makefile

Makefile helper to reset the database, regenerate prisma client and do npm install in frontend and backend directories. 
Hopefully useful when switching between branches with database changes.

chore: add make reset_project command

---

frontend/src/components/rec-resource/RecResourcePage.tsx
frontend/src/components/rec-resource/section/Camping.tsx
frontend/src/components/rec-resource/section/MapsAndLocation.tsx

Just a quick follow up PR, I got caught out by a classic short circuit conditional rendering bug since campsite_count is 0
Fixed types conditionals as well, I found a site that didn't have any and just showed the heading with nothing else.

fix: campsite conditional short circuit 0 error

---

frontend/e2e/poms/layout.ts
frontend/src/components/layout/Header.scss
frontend/src/components/layout/Header.tsx
frontend/src/data/urls.ts

Made changes to the header nav component as per the new figma design:
1. Added link to interactive map view. 
2. Removed `Contact` link

feat(header-nav): added link to interactive map

---

frontend/src/components/rec-resource/RecResourcePage.tsx
frontend/src/components/rec-resource/section/SiteDescription.test.tsx
frontend/src/components/rec-resource/section/SiteDescription.tsx

Update the name `Maintenance standard` to `Maintenance type` as well as fix camping anchor tag bug

chore: rename maintenance standard section to maintenance type

---

.github/workflows/main.yml
backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json
infrastructure/api/ecs.tf
infrastructure/database/aurora-v2.tf

Went through the alerts with Om and fixed the ones we thought were relevant:
- Enable RDS performance insights
- Enable ECS container insights
- RDS deletion protection for prod is handled in #544 
- Update Vite and NestJS

chore: fix code scanning alerts

---

backend/src/recreation-resource/constants/service.constants.ts
backend/src/recreation-resource/utils/formatRecreationResourceDetailResults.spec.ts
backend/src/recreation-resource/utils/formatRecreationResourceDetailResults.ts
backend/src/recreation-resource/utils/formatSearchResults.spec.ts
backend/src/recreation-resource/utils/formatSearchResults.ts
frontend/src/components/rec-resource/card/RecResourceCard.tsx

Considered doing a view as a source of truth similar to `recreation_type` but I don't think that would work as unlike the type, the issue with status is that a lot of sites just don't have entries at all. Since prisma doesn't support `coalesce` I'm just handling it when we format the data.
- **fix: display rec resources with no status as open**
- **fix: rec resource card status alignment when no activities**
Also fixed the alignment when there were no activities, the status was on the left of the card:
Fixed:

fix: site status

---

.github/workflows/.e2e.yml
.github/workflows/main.yml
frontend/e2e/constants.ts
frontend/e2e/poms/components/filter.ts
frontend/e2e/poms/pages/recResource.ts
frontend/e2e/poms/pages/search.ts
frontend/e2e/poms/pages/types.ts
frontend/e2e/workflows/search/filter.spec.ts
frontend/e2e/workflows/search/search.spec.ts

#337
- the e2e workflow can run e2e locally ie docker-compose or using a live base url passed in via environment secrets
- e2e tests now run against the dev environment after dev has been deployed
- e2e tests now run against the test environment after test has been deployed
- I may change this but both dev and test e2e use a new project `rst-dev`. Theoretically they should be the same so I think we can use the same one, but we will see how it goes and I can create another `rst-test` if needed
- Tests are rewritten to work against both the dev fixtures and the live data
- Instead of verifying specific results, or the number of results we are verifying that there are results
- Verifying that each search results card contains the text that was searched for
- For filters, we are intercepting …

ci: run e2e tests on dev after deployment

---

frontend/src/components/layout/PageMenu.scss
frontend/src/components/layout/PageMenu.tsx
frontend/src/components/rec-resource/RecResourcePage.tsx

#530 
This issue was originally meant to add a dropdown menu for mobile though we noticed that bcparks.ca got rid of that. Now we are more closely aligning with their menu with the `On this page` header and the mobile styling.
Desktop:
Mobile:

chore: update page menu mobile styling

---

frontend/src/components/recreation-search-form/RecreationSearchForm.test.tsx
frontend/src/components/recreation-search-form/RecreationSearchForm.tsx
frontend/src/components/search/NoResults.test.tsx
frontend/src/components/search/NoResults.tsx

Add a `Go back to the full list` button I missed in the 'no search results' component. Initially I had just added a link back to `/search` though since it was the same page and triggered a full page load it caused some weird flashing. 
I did it the proper way and cleared the search params, making for a smoother ux.

chore: add no results component button

---

frontend/src/App.tsx

Addressed an accessibility issue where keyboard users were unable to bypass repeated content (e.g., headers, navigation) to quickly reach the main content of the page. This was a failure of [WCAG 2.1 Success Criterion 2.4.1 – Bypass Blocks](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html).
---
- Added a "Skip to main content" link at the top of the page
- Styled the link to be visually hidden and only visible when focused (accessible via keyboard)
- Linked the skip link to the `#main-content` anchor on the primary content container
---
1. Navigate to the page using only the keyboard (Tab key).
2. On page load, the first focusable element should be a "Skip to main content" link.
3. Activating the link (Enter/Return) should move focus directly to the main content.

feat(accessibility): add "Skip to main content" link for keyboard navigation

---

.github/workflows/fta-migration.yml

- Remove dev from the nightly fta scheduler. Dev will inevitably be broken at some points so I don't want it to impede prod being up to date
- Change unused workflow_call to workflow_dispatch so it can be called manually

ci: remove dev from fta migration scheduler

---

frontend/src/components/layout/PageMenu.scss
frontend/src/components/layout/PageMenu.test.tsx
frontend/src/components/rec-resource/RecResource.scss
frontend/src/components/rec-resource/RecResourcePage.tsx
frontend/src/components/recreation-search-form/RecreationSearchForm.scss
frontend/src/components/recreation-search-form/RecreationSearchForm.tsx
frontend/src/styles/variables.scss

Combined a few tiny bug fix prs here, #647, #658, #589
- Reduce mobile page padding from 2rem/32px to 1rem/16px
- Reduce rec resource page menu top and bottom margins on mobile
- Fix bug in medium viewport size/tablet mode where the page menu would take up most of the screen
- Fix some regression I made in the landing page search bar - these only happened in firefox and safari

fix: rec resource page menu and mobile padding

---

frontend/src/components/layout/BreadCrumbs.test.tsx
frontend/src/components/layout/BreadCrumbs.tsx
frontend/src/components/rec-resource/RecResourcePage.tsx
frontend/src/service/queries/recreation-resource/recreationResourceQueries.ts

[#661](https://github.com/bcgov/nr-rec-resources/issues/661)
Also refactored the breadcrumbs to be static - we are only using them on the rec resource page so there was no need for them to be dynamic. I was having to add all these checks and conditionals to add the history to the search url and it seemed bug prone and overcomplicated. Let me know if you think I should revert it.

chore: bread crumb search page link has search history

---

backend/src/recreation-resource/service/recreation-resource-search.service.spec.ts
backend/src/recreation-resource/service/recreation-resource-search.service.ts
backend/src/recreation-resource/service/types.ts
backend/src/recreation-resource/utils/buildFilterMenu.spec.ts
backend/src/recreation-resource/utils/buildFilterMenu.ts
backend/src/recreation-resource/utils/buildRecreationResourcePageQuery.spec.ts
backend/src/recreation-resource/utils/buildRecreationResourcePageQuery.ts
backend/src/recreation-resource/utils/buildSearchFilterOptionCountsQuery.spec.ts
backend/src/recreation-resource/utils/buildSearchFilterOptionCountsQuery.ts
backend/src/recreation-resource/utils/buildSearchFilterQuery.spec.ts
backend/src/recreation-resource/utils/buildSearchFilterQuery.ts
frontend/e2e/workflows/search/filterChips.spec.ts
frontend/package.json
frontend/src/components/search/filters/FilterGroup.test.tsx
frontend/src/components/search/filters/FilterGroup.tsx
frontend/src/components/search/filters/FilterMenu.test.tsx

**Implemented Dynamic Filter Counts**
Here's how filters work:
**Starting View**
When you first view the list, each filter displays the total number of items in its **category**. Categories include **district**, **type**, **access**, **activities**, and **facilities**.
**Using Multiple Filters**
- When you select filters from **different categories** (like "North District" and "Hiking"), you'll see only items that match **all** your selections. The filter counts across all categories will reflect the **narrowed-down count** of possible results.
- When you select **multiple options in the same category** (like "Hiking" and "Camping") and if that category is either district, access, or type, you'll see items that match **any** of those options. The filter counts for each option *within this …

feat(search-filters): implement dynamic filter aggregation logic

---

frontend/src/components/rec-resource/card/CardCarousel.tsx
frontend/src/components/rec-resource/card/RecResourceCard.scss
frontend/src/components/rec-resource/card/helpers.test.ts
frontend/src/components/rec-resource/card/helpers.ts
frontend/src/components/recreation-search-form/RecreationSearchForm.tsx
frontend/src/components/search/filters/FilterMenuMobile.tsx
frontend/src/components/search/filters/Filters.scss

- Use `object-fit: cover` on the mobile search card images just as we do for desktop
- Sort image variants by landscape first since they look/fit better with our card design which has the images with more width than height. This way the more zoomed in portrait images aren't displayed first.
- Update mobile filter styles to closer align with bcparks.ca
Update to how we handle images in the mobile search cards. 
Some sites currently show portait images like this:
Now we sort images to show landscape first since they aren't so zoomed in:
Then we use `object-fit: cover` to display portrait images just like we do on desktop:
Minor updates filter styles to more closely align with bcparks. Minor differences in colour due to acessibility/contrast.
Bcparks:

chore: mobile search image and filter style improvements

---

frontend/src/components/recreation-search-form/LocationSearch.tsx
frontend/src/components/recreation-search-form/RecreationSearchForm.test.tsx
frontend/src/components/recreation-search-form/RecreationSearchForm.tsx
frontend/src/components/search/SearchPage.tsx
frontend/src/service/queries/recreation-resource/recreationResourceQueries.ts

Breadcrumb history now includes `community` param so the new location search input is populated on return. This had to be handled as that param isn't used by used by the api so the type wasn't autogenerated.
Also added `position: relative` to the name input container so the clear input button is inside the input as it previously was:

fix: community search param excluded from breadcrumb history

---

.github/workflows/.build.yml
.github/workflows/.tests.yml
.github/workflows/build-deploy-el-openshift.yml

This PR removes `bcgov-nr` references for reusable GHA as the org is deprecated and all actions are now moved under `bcgov`

chore: remove bcgov-nr references

---

Makefile
public/frontend/src/components/StyledVectorFeatureMap/StyledVectorFeatureMap.tsx
public/frontend/src/components/StyledVectorFeatureMap/components/MapControls.test.tsx
public/frontend/src/components/StyledVectorFeatureMap/components/MapControls.tsx
public/frontend/src/components/StyledVectorFeatureMap/constants.ts
public/frontend/src/components/StyledVectorFeatureMap/hooks/useAddVectorLayerToMap.ts
public/frontend/src/components/rec-resource/RecreationResourceMap/RecreationResourceMap.test.tsx
public/frontend/src/components/rec-resource/RecreationResourceMap/RecreationResourceMap.tsx
public/frontend/src/components/rec-resource/RecreationResourceMap/constants.ts
public/frontend/src/components/rec-resource/RecreationResourceMap/helpers/index.ts
public/frontend/src/components/rec-resource/RecreationResourceMap/helpers/mapDownloadHandlers.test.ts
public/frontend/src/components/rec-resource/RecreationResourceMap/helpers/mapDownloadHandlers.ts
public/frontend/src/components/rec-resource/section/MapsAndLocation.test.tsx
public/frontend/src/components/rec-resource/section/MapsAndLocation.tsx
public/frontend/src/utils/fileUtils.test.ts
public/frontend/src/utils/fileUtils.ts

- add kml and gpx download functionality for the rec resource map
- removed zoom animation on the map
---

feat(rec-resource-map): add kml and gpx download functionality

---

public/frontend/src/components/rec-resource/card/RecResourceCard.scss

#821
Always show navigation buttons on mobile:
Desktop remains the same, need to hover to show them:

fix: always show card carousel navigation buttons on mobile

---

.github/workflows/.deploy-app.yml
terraform/frontend/admin-dev/terragrunt.hcl
terraform/frontend/admin-prod/terragrunt.hcl
terraform/frontend/admin-test/terragrunt.hcl
terraform/frontend/public-dev/terragrunt.hcl
terraform/frontend/public-prod/terragrunt.hcl
terraform/frontend/public-test/terragrunt.hcl

- Added DAM test and prod urls to the Content Security Policies for the respective environment
- Added the DAM url as repository secret in Github
```
gh secret set VITE_RECREATION_RESOURCE_ASSETS_BASE_URL --body="https://dam.lqc63d-test.nimbus.cloud.gov.bc.ca" --env test
gh secret set VITE_RECREATION_RESOURCE_ASSETS_BASE_URL --body="https://dam.lqc63d-test.nimbus.cloud.gov.bc.ca" --env dev
gh secret set VITE_RECREATION_RESOURCE_ASSETS_BASE_URL --body="https://dam.lqc63d-prod.nimbus.cloud.gov.bc.ca" --env prod
```

ci(security-csp): added dam urls to csp policy

---

terraform/frontend/admin-dev/terragrunt.hcl
terraform/frontend/admin-test/terragrunt.hcl
terraform/frontend/public-dev/terragrunt.hcl
terraform/frontend/public-test/terragrunt.hcl

full domain names are required for csp to work properly. the wildcard used in the previous PR was incorrect.

fix(csp): use full domain name instead of wild cards

---

.github/workflows/.review-and-deploy.yml

[#1055](https://github.com/bcgov/nr-rec-resources/issues/1055)
Create 4 new GitHub environments for reviewing deployments:
- `review-admin-test-deployment`
- `review-admin-prod-deployment`
- `review-public-test-deployment`
- `review-public-prod-deployment`
TODO after merge:
- delete `review-test-deployment` and `review-prod-deployment` environments

ci: separate admin and public deployment review environments

---

.github/workflows/.deploy-app.yml

Separate upload of `index.html` and add `no-cache, must-revalidate` cache control headers to that file to hopefully mitigate the issue Airlia ran into after prod deployment.
using `no-cache` instead of `no-store` as it is less strict - it still allows the browser to temporarily cache but we force the browser to revalidate before using it.
Vite hashes all the asset names so we should be good to cache everything else.

ci: add cache-control headers during cloudfront s3 sync

---

admin/frontend/src/components/rec-resource-suggestion-form/SuggestionListItem.tsx
admin/frontend/test/components/rec-resource-suggestion-form/SuggestionListItem.test.tsx
public/frontend/src/components/recreation-suggestion-form/SuggestionListCity.test.tsx
public/frontend/src/components/recreation-suggestion-form/SuggestionListCity.tsx
public/frontend/src/components/recreation-suggestion-form/SuggestionListItem.test.tsx
public/frontend/src/components/recreation-suggestion-form/SuggestionListItem.tsx
shared/src/components/suggestion-typeahead/SuggestionListItem.scss

Airlia noticed that mobile styling was broken in PO review.
Before:
After:

fix: search typeahead form mobile styles

---

admin/backend/src/app-config/app-config.schema.ts
admin/backend/src/app-config/app-config.service.ts
infrastructure/api/ecs.tf

Modify the PostgreSQL schema environment variable in the backend configuration to ensure it is correctly referenced and used throughout the application.

fix(backend-env-vars): modify the postgres schema env var in terraform config

---

infrastructure/frontend/cloudfront.tf

Update the Content Security Policy to permit blob URLs in image tags, enhancing the flexibility of image sources.

fix(csp-images): adjust csp policy to allow blob links in img tags

---

terraform/frontend/admin-dev/terragrunt.hcl
terraform/frontend/admin-prod/terragrunt.hcl
terraform/frontend/admin-test/terragrunt.hcl
terraform/frontend/public-dev/terragrunt.hcl
terraform/frontend/public-prod/terragrunt.hcl
terraform/frontend/public-test/terragrunt.hcl

Incorporate new Matomo LZA URLs into the Content Security Policy across development, production, and test configurations.

feat(csp): add new matomo lza urls to csp policy

---

public/frontend/src/components/recreation-suggestion-form/RecreationSuggestionForm.test.tsx
public/frontend/src/components/recreation-suggestion-form/RecreationSuggestionForm.tsx
public/frontend/src/components/recreation-suggestion-form/SuggestionListCity.test.tsx
public/frontend/src/components/recreation-suggestion-form/SuggestionListCity.tsx
shared/src/components/suggestion-typeahead/SuggestionTypeahead.tsx

Fix for: https://bcparksdigital.atlassian.net/browse/ORCA-101
The search input should now persist between list and map view. The landing page should always be clear when returning to it. 
Also has a few very minor text updates.

fix: persist search input value between list and map view

---

public/frontend/src/components/rec-resource/card/RecResourceCard.scss
public/frontend/src/components/rec-resource/card/RecResourceCard.tsx
public/frontend/src/components/search-map/preview/MapFeaturePreview.scss

Fix for the `see all` showing in the map preview card. We aren't showing any activities at all but this slipped through. I added the flex styles to the `.card-activities` class so the bootstrap `display: flex` wouldn't override `display: none` when I set it in the preview card.
Issue:

fix: map preview card see all showing

---

public/frontend/src/components/search-map/SearchViewControls.tsx
public/frontend/src/components/search/SearchPage.test.tsx
public/frontend/src/components/search/SearchPage.tsx

https://bcparksdigital.atlassian.net/jira/software/projects/ORCA/boards/22?selectedIssue=ORCA-39
The `NoResults` component was temporarily mounting and calling the useEffect which was causing focus and scrolling down on mobile even though the component wasn't visible at all. Even though `totalCount === undefined` doesn't actually seem to exist even if we log it, I believe it was happening extremely briefly on `SearchPage` mount before the default search store `totalCount` of 0 was populated.
Removed `totalCount === undefined` check as it wasn't doing anything - even if I completely turn off the backend totalCount will resolve as 0.

fix: search page scrolls to results on search page initial load

---

.github/workflows/fta-migration.yml

Added this while we debugged the FTA migration though decided to keep it incase we need it in the future. Removed the schedule and improved the workflow dispatch options. Now we can choose to manually deploy to dev, test or prod:

chore: remove fta migration scheduled action and refactor workflow dispatch

---

public/frontend/src/components/recreation-suggestion-form/SuggestionMenu.scss
public/frontend/src/components/recreation-suggestion-form/SuggestionMenu.tsx

After discussion with Harry and Airlia we decided to shorten the suggestion menu on mobile since items at the bottom were obscured by the on screen keyboard.

fix: shorten suggestion menu on mobile

---

terraform/migration/terragrunt.hcl

Since migrations is used by both apps, we need to keep a unified app name for things like our OpenShift imports to reference. Every time we push migrations to admin, it is deleting the fta migration task definition and breaking OpenShift migrations.

ci(fix): use unified app name for migrations

---

migrations/fta/sql/V1.0.4__fta_to_rst_activity.sql
migrations/fta/sql/V1.0.6__fta_to_rst_access.sql
migrations/fta/sql/V1.0.7__fta_to_rst_structure.sql
migrations/fta/sql/V1.0.8__fta_to_rst_fee.sql
migrations/fta/sql/V1.0.9__fta_to_rst_campsite.sql
migrations/fta/sql/V1.1.17__fta_to_rstrecreation_agreement_holder.sql

Delete obsolete rows in activities and some other tables. Tested each of these in dev and there were changes in each of the tables, from 1 row to about 20 depending. 
Camping activity is gone from https://dz37sfd9duckr.cloudfront.net/resource/REC106349 (this will get overridden if someone pushes to dev again)

fix: migrations delete obsolete rows

---

public/frontend/src/components/rec-resource/RecResourceReservation.scss
public/frontend/src/components/rec-resource/RecResourceReservation.tsx

Difference in dev data vs the actual data revealed a minor accessibility issue when e2e runs on dev. The `additional fees` url doesn't show up on our dev data so the test passed fine on our local and PR e2e in CI.
Tested deploying and running this on dev here:
https://github.com/bcgov/nr-rec-resources/actions/runs/17744568995/job/50427121275

fix: axe e2e link-in-text-block accessibility error

---

public/frontend/src/components/rec-resource/RecResourcePage.tsx
public/frontend/src/components/rec-resource/RecResourceReservation.test.tsx
public/frontend/src/components/rec-resource/RecResourceReservation.tsx
public/frontend/src/components/rec-resource/section/KnowBeforeYouGo.scss
public/frontend/src/components/rec-resource/section/KnowBeforeYouGo.test.tsx
public/frontend/src/components/rec-resource/section/KnowBeforeYouGo.tsx

Final adjustments after call with @BAAlexK 
- Consider recreation fee (camping fee) as a condition to fees on reservation and Know Before you know sessions
- Change Know Before you know session visibility to only Recreation sites
- Few text adjustments and conditionals for more elegant display (colons, and, spaces).

chore: last fixes for reservations

---

admin/backend/prisma/schema.prisma
migrations/fixtures/sql/V1.0.0__recreation_resource.sql
migrations/fta/sql/V1.0.2__fta_to_rst_rec_resource.sql
migrations/fta/sql/V1.1.18__fta_to_recreation_control_access_code.sql
migrations/rst/sql/V1.1.34__recreation_control_access_code.sql

- Add migration scripts to import `fta.recreation_control_access_code` table into rst schema 
- add history table for this new table
- added new column in `rst.recreation_resource` which refers to `rst.recreation_control_access_code`

feat(migrations): add migration scripts for recreation control access code

---

migrations/fta/sql/V1.1.18__fta_to_recreation_control_access_code.sql

- `rst.recreation_control_access_code` table was being seeded twice which lead to db contratint errors during flyway migrations. so this pr removes the unwanted script

fix(fta-migrations): remove unwanted fta to rst migration script for control access code

---

public/frontend/src/components/layout/Footer.scss
public/frontend/src/components/layout/HamburgerButton.scss
public/frontend/src/components/layout/HamburgerButton.test.tsx
public/frontend/src/components/layout/HamburgerButton.tsx
public/frontend/src/components/layout/Header.scss
public/frontend/src/components/layout/Header.test.tsx
public/frontend/src/components/layout/Header.tsx
public/frontend/src/components/layout/NavigationDrawer.scss
public/frontend/src/components/layout/NavigationDrawer.test.tsx
public/frontend/src/components/layout/NavigationDrawer.tsx
public/frontend/src/components/layout/PageMenu.scss
public/frontend/src/components/layout/ScrollToTop.scss
public/frontend/src/components/layout/constants.ts
public/frontend/src/components/notifications/NotificationToast.scss
public/frontend/src/components/rec-resource/PhotoGallery.scss
public/frontend/src/components/rec-resource/RecreationResourceMap/MapDisclaimerModal.scss
public/frontend/src/components/recreation-suggestion-form/RecreationSuggestionForm.scss
public/frontend/src/components/search-map/SearchMap.scss
public/frontend/src/components/search/filters/FilterMenuSearchMap.scss
public/frontend/src/components/search/filters/Filters.scss
public/frontend/src/data/urls.ts
public/frontend/src/styles/variables.scss
shared/src/hooks/index.ts
shared/src/hooks/useClickOutside.ts
shared/src/index.ts
shared/src/test/hooks/useClickOutside.test.ts

Add new sub header links and mobile navigation menu

feat: add extra sub header links and create mobile navigation menu

---

admin/backend/src/recreation-resource/recreation-resource.service.ts

Display resources with no districts on suggestion.
This cover the case of REC0001 not being shown on admin suggestions.

chore: display suggestions with no districts

---

migrations/rst/sql/V1.1.36__enable_pg_trgm_extension.sql
package-lock.json
public/backend/src/recreation-resource/service/recreation-resource-search.service.ts
public/backend/src/recreation-resource/service/recreation-resource-suggestion.service.spec.ts
public/backend/src/recreation-resource/service/recreation-resource-suggestion.service.ts
public/backend/src/recreation-resource/utils/buildRecreationResourcePageQuery.ts
public/backend/src/recreation-resource/utils/buildSearchFilterQuery.spec.ts
public/backend/src/recreation-resource/utils/buildSearchFilterQuery.ts
public/backend/src/recreation-resource/utils/fuzzySearchUtils.ts
public/frontend/e2e/poms/pages/landing.ts
public/frontend/e2e/workflows/search/filter.spec.ts
public/frontend/e2e/workflows/search/search.spec.ts
public/frontend/e2e/workflows/user/landing-search.spec.ts
public/frontend/package.json
public/frontend/src/components/recreation-suggestion-form/RecreationSuggestionForm.test.tsx
public/frontend/src/components/recreation-suggestion-form/RecreationSuggestionForm.tsx
public/frontend/src/components/recreation-suggestion-form/hooks/useSearchInput.ts
public/frontend/src/utils/fuzzySearch.test.ts
public/frontend/src/utils/fuzzySearch.ts

- add fuzzy search to front end city search using [fuse.js](https://www.fusejs.io/)
- add fuzzy search to backend search and suggestions using `pg_trgm` similarity
- update e2e tests that were failing in dev due to district changes (okanagan district is empty now)
- update e2e tests due to fuzzy search changes

feat: fuzzy search

---

public/frontend/src/components/search-map/SearchMap.tsx
public/frontend/src/components/search-map/hooks/useClusteredRecreationFeatureLayer.test.ts
public/frontend/src/components/search-map/hooks/useClusteredRecreationFeatureLayer.ts
public/frontend/src/components/search-map/hooks/useZoomToExtent.test.ts
public/frontend/src/components/search-map/hooks/useZoomToExtent.ts
public/frontend/src/components/search-map/styles/cluster.test.ts
public/frontend/src/components/search-map/styles/cluster.ts
public/frontend/src/components/search-map/utils/calculateMapPadding.ts
public/frontend/src/components/search-map/utils/index.ts

Clusters are the same size now and adjusted the padding when you zoom to them and they uncluster so the new points aren't off screen.

chore: map clustering updates

---

.github/workflows/.release.yml
.github/workflows/.review-and-deploy.yml
.github/workflows/main.yml

Okay, last one I think. Since we have no easy way to separate admin/public commits I'm not sure it makes sense to have separate releases.
My idea for this now is to schedule releases on the first of every month as well as add the ability to manually trigger them from the actions tab. We can decide as a team when to make releases (besides the automated monthly ones) and manually call them.

ci: change release workflow to scheduled and manual dispatch
